"""
Staff Comparison Report - Liste vs Database
Erkan için hazırlandı
"""

# Listedeki personeller (Excel'den)
excel_staff = [
    "MAHPERİ KURT",
    "Tuğçe Kirenli",
    "SALiH SEVIKA",
    "RAMAZAN NURYA",
    "ÖZGÜR ÖZGÜN",
    "Cihan Erdoğan",
    "YAŞAR ATAMKOÇYİĞİT",
    "Ali Gezer",
    "FURKAN YILDIRIM",
    "Halit Bağış",
    "ERANCAN TURAN",
    "Bilal Iqbal",
    "Orhan Atlı",
    "EREN ÖNDER",
    "Ramazan Doğanay",
    "Nur Absal",
    "SEFA FARUK",
    "MUSTAFA BAŞKALE",
    "Sergen Elmas",
    "UGUR CAN DELİBAŞ",
    "Salman Ali",
    "EMİRHAN BOYRAZ",
    "Muhammed Abdullah",
    "BÜNYAMİN AYDIN",
    "Muhammed Wassem",
    "SİBEL ATASOY",
    "ONURCAN KOYUN",
    "Hüseyin Tülegen",
    "FERYAL YAMAN",
    "ZEYNEP OKUR",
    "OĞUZHAN ELMAS",
    "İNANÇ KOÇAK",
    "TUGBA ILBAY",
    "SILA KUVAT",
    "AZİZ DEMHAT",
    "CANER OZKAN KUTLU",
    "YUSUF ŞAHİN",
    "MEHMET KOÇAK",
    "FERAY YAKICI",
    "EZGİ KAŞIKÇI",
    "M.ALİ KARASU",
    "HAKAN CİNTOSUN",
    "KAAN TONYALIOĞLU",
    "KAZIM KOCA",
    "ONUR NAMA",
    "ŞEVVAL EROL",
    "M. AKİF ŞİMŞEK",
    "KEREM ERTÜRK",
    "AYTEKİN SARITOPRAK",
    "BARIŞ TÜZÜN",
    "AHMET CAN FINDICAK",
    "ÖMER İNCE",
    "Ahmet Deste",
    "ALİ DÖNMEZ",
    "CAFER MELİH YEL",
    "MEHMET YILDIRIM",
    "YILDIZ AĞIRMAN",
]

# Veritabanındaki personeller
db_staff = [
    "Ahmet Can Fındıcak",
    "Ali Dönmez",
    "Aytekin Sarıtoprak",
    "Aziz Demhat Yılmaz",
    "Barış Tüzün",
    "Bünyamin Aydın",
    "Cafer Melih Yel",
    "Caner Özkan Kutlu",
    "Emirhan Boyraz",
    "Erencan Turan",
    "Ezgi Çağla Kaşıkçı",
    "Feray Yakıcı",
    "Feryal Yaman",
    "Furkan Yıldırım",
    "Hakan Cintosun",
    "Kaan Tonyalıoğlu",
    "Kazım Koca",
    "Kerem Ertürk",
    "Mehmet Akif Şimşek",
    "Mehmet Ali Deste",
    "Mehmet Ali Karasu",
    "Mehmet Koçak",
    "Mehmet Yıldırım",
    "Mustafa Başkale",
    "Oğuzhan Elmas",
    "Onur Nama",
    "Onurcan Koyun",
    "Orhan Atlı",
    "Özgür Özgün",
    "SALiH  SEVIKA",
    "Sefa Faruk Kurt",
    "Sibel Atasoy",
    "Sıla Kuvat",
    "Tuğba İlbay",
    "Tuğçe Kirenli",
    "Uğur Can Delibaş",
    "Yaşar Atamkoçyiğit",
    "Yusuf Şahin",
    "Yıldız Ağırman",
    "Zeynep Ebru Okur",
    "Ömer İnce",
    "İnanç Koçak",
    "Şevval Erol",
]

print("=" * 80)
print("STAFF KARŞILAŞTIRMA RAPORU")
print("=" * 80)
